version: '3.1'

services:
  web:
    build: .
    volumes:
      - .:/app
      - yarn_cache:/app/node_modules
    working_dir: /app
    ports:
      - '3000:3000' # dev server
      - '5000:5000' # prod build server
    stdin_open: true
    tty: true

volumes:
  yarn_cache:
